apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ingress-controllers
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: ingress-infra
            namespace: ingress-infra
            ingressClass: infra
            nodeRole: infra
          - name: ingress-external
            namespace: ingress-external
            ingressClass: external
            nodeRole: infra
          - name: ingress-internal
            namespace: ingress-internal
            ingressClass: internal
            nodeRole: infra
  template:
    metadata:
      name: "{{name}}"
      labels:
        app.kubernetes.io/part-of: ingress
        app.kubernetes.io/managed-by: applicationset
    spec:
      project: default
      source:
        repoURL: https://kubernetes.github.io/ingress-nginx
        chart: ingress-nginx
        targetRevision: 4.14.3
        helm:
          values: |
            controller:
              ingressClassResource:
                name: {{ingressClass}}
              ingressClass: {{ingressClass}}
              nodeSelector:
                role: {{nodeRole}}
              tolerations:
                - key: "role"
                  operator: "Equal"
                  value: {{nodeRole}}
                  effect: "NoSchedule"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true