apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability
  namespace: argocd-infra
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true,Replace=true
spec:
  project: default
  source:
    repoURL: https://github.com/GabrielHM98/cloud-engineering.git
    targetRevision: master
    path: aks/gitops/observability
    helm:
      valueFiles:
        - values.yaml
      values: |
        grafana:
          nodeSelector:
            role: infra
        thanos:
          nodeSelector:
            role: infra
        kube-prometheus-stack:
          nodeSelector:
            role: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /metadata/annotations