apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-external
  namespace: ingress-external
spec:
  project: default
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.10.0
    helm:
      values: |
        controller:
          ingressClassResource:
            name: external
          ingressClass: external
          nodeSelector:
            role: infra
          tolerations:
            - key: "role"
              operator: "Equal"
              value: "infra"
              effect: "NoSchedule"
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-external
  syncPolicy:
    automated:
      prune: true
      selfHeal: true