apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-stack
  namespace: argocd-infra
spec:
  project: default
  source:
    repoURL: https://github.com/GabrielHM98/cloud-engineering.git
    targetRevision: master
    path: infra-gitops/observability/release
    helm:
      valueFiles:
        - values.yaml
      values: |
        grafana:
          nodeSelector:
            role: infra
          tolerations:
            - key: "role"
              operator: "Equal"
              value: "infra"
              effect: "NoSchedule"
        thanos:
          nodeSelector:
            role: infra
          tolerations:
            - key: "role"
              operator: "Equal"
              value: "infra"
              effect: "NoSchedule"            
        kube-prometheus-stack:
          nodeSelector:
            role: infra
          tolerations:
            - key: "role"
              operator: "Equal"
              value: "infra"
              effect: "NoSchedule"            
  destination:
    server: https://kubernetes.default.svc
    namespace: observability-stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /metadata/annotations