apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-internal
  namespace: ingress-internal
spec:
  project: default
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.10.0
    helm:
      values: |
        controller:
          ingressClassResource:
            name: internal
          ingressClass: internal
          service:
            type: LoadBalancer
            annotations:
              service.beta.kubernetes.io/azure-load-balancer-internal: "true"
          nodeSelector:
            role: infra
          tolerations:
            - key: "role"
              operator: "Equal"
              value: "infra"
              effect: "NoSchedule"
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-internal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
