# This rule is not used by the project downscaler-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over monitoring.example.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: downscaler-operator
    app.kubernetes.io/managed-by: kustomize
  name: downscaler-admin-role
rules:
- apiGroups:
  - monitoring.example.com
  resources:
  - downscalers
  verbs:
  - '*'
- apiGroups:
  - monitoring.example.com
  resources:
  - downscalers/status
  verbs:
  - get
