apiVersion: monitoring.example.com/v1alpha1
kind: Downscaler
metadata:
  labels:
    app.kubernetes.io/name: downscaler-operator
    app.kubernetes.io/managed-by: kustomize
  name: downscaler-sample
spec:
  # TODO(user): Add fields here
